import type { ReactNode } from "react"
import { useEffect, useState } from "react"
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router"
import { requireActiveAdmin } from "@/features/admin/requireAdmin"
import { formatCad, formatDate } from "@/features/admin/formatters"
import { supabase } from "@/lib/supabase"

export const Route = createFileRoute("/admin/customers/$customerId")({ component: CustomerDetailPage })

type Customer = { id: string; first_name: string; last_name: string | null; email: string; phone: string | null; address_line: string | null; city: string | null; province: string | null; postal_code: string | null; status: string | null; internal_notes: string | null; created_at: string }
type Estimate = { id: string; estimate_number: string; status: string; total: number; created_at: string }
type Request = { id: string; request_number: number; service_name: string | null; status: string; created_at: string }

function CustomerDetailPage() {
  const { customerId } = Route.useParams(); const navigate = useNavigate()
  const [customer, setCustomer] = useState<Customer | null>(null); const [estimates, setEstimates] = useState<Estimate[]>([]); const [requests, setRequests] = useState<Request[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  useEffect(() => { void load() }, [customerId])
  async function load() { setLoading(true); try { if (!(await requireActiveAdmin())) { await navigate({ to: "/admin/login" }); return } const [customerResult, estimatesResult, requestsResult] = await Promise.all([supabase.from("customers").select("id, first_name, last_name, email, phone, address_line, city, province, postal_code, status, internal_notes, created_at").eq("id", customerId).maybeSingle(), supabase.from("estimates").select("id, estimate_number, status, total, created_at").eq("customer_id", customerId).order("created_at", { ascending: false }), supabase.from("service_requests").select("id, request_number, service_name, status, created_at").eq("customer_id", customerId).order("created_at", { ascending: false })]); if (customerResult.error) throw customerResult.error; if (!customerResult.data) throw new Error("Client introuvable."); if (estimatesResult.error) throw estimatesResult.error; if (requestsResult.error) throw requestsResult.error; setCustomer(customerResult.data as Customer); setEstimates((estimatesResult.data ?? []) as Estimate[]); setRequests((requestsResult.data ?? []) as Request[]) } catch (caught) { setError(caught instanceof Error ? caught.message : "Impossible de charger le client.") } finally { setLoading(false) } }
  if (loading) return <p className="text-slate-600">Chargement du client…</p>
  if (!customer) return <div className="rounded-lg border border-red-200 bg-red-50 p-5 text-red-800">{error || "Client introuvable."}</div>
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link to="/admin/customers" className="text-sm font-semibold text-blue-700 hover:underline">← Retour aux clients</Link><h1 className="mt-2 text-3xl font-bold text-slate-950">{customer.first_name} {customer.last_name ?? ""}</h1><p className="text-slate-600">Client depuis le {formatDate(customer.created_at)}</p></div><Link to="/admin/estimates/new" search={{ customerId: customer.id }} className="rounded-lg bg-emerald-600 px-4 py-2.5 font-semibold text-white">Créer un devis</Link></header>{error && <div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}<div className="grid gap-6 lg:grid-cols-3"><section className="rounded-xl border bg-white p-5 shadow-sm lg:col-span-1"><h2 className="text-lg font-bold">Coordonnées</h2><dl className="mt-4 space-y-4 text-sm"><Info label="Courriel" value={customer.email} /><Info label="Téléphone" value={customer.phone} /><Info label="Adresse" value={[customer.address_line, customer.city, customer.province, customer.postal_code].filter(Boolean).join(", ")} /><Info label="Statut" value={customer.status} /></dl>{customer.internal_notes && <div className="mt-5 border-t pt-4"><p className="text-sm font-semibold">Notes internes</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{customer.internal_notes}</p></div>}</section><div className="space-y-6 lg:col-span-2"><Related title="Devis officiels" empty="Aucun devis officiel pour ce client.">{estimates.map((estimate) => <Link key={estimate.id} to="/admin/estimates/$estimateId" params={{ estimateId: estimate.id }} className="flex items-center justify-between border-b px-4 py-3 last:border-0 hover:bg-slate-50"><div><p className="font-semibold">{estimate.estimate_number}</p><p className="text-sm text-slate-500">{formatDate(estimate.created_at)} · {estimate.status}</p></div><p className="font-bold">{formatCad(estimate.total)}</p></Link>)}</Related><Related title="Demandes de devis" empty="Aucune demande rattachée à ce client.">{requests.map((request) => <Link key={request.id} to="/admin/quotes/$requestId" params={{ requestId: request.id }} className="flex items-center justify-between border-b px-4 py-3 last:border-0 hover:bg-slate-50"><div><p className="font-semibold">Demande #{request.request_number}</p><p className="text-sm text-slate-500">{request.service_name ?? "Service non précisé"}</p></div><span className="text-sm text-slate-600">{request.status}</span></Link>)}</Related></div></div></div>
}
function Info({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-900">{value || "—"}</dd></div> }
function Related({ title, empty, children }: { title: string; empty: string; children: ReactNode }) { const hasChildren = Array.isArray(children) ? children.length > 0 : Boolean(children); return <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><h2 className="border-b px-5 py-4 text-lg font-bold">{title}</h2>{hasChildren ? children : <p className="p-5 text-sm text-slate-500">{empty}</p>}</section> }
