import { useEffect, useState } from "react"
import { createFileRoute } from "@tanstack/react-router"
import { supabase } from "@/lib/supabase"
import { formatCad, formatDate } from "@/features/admin/formatters"

export const Route = createFileRoute("/admin/contracts/")({ component: ContractsPage })
type Contract={id:string;title:string;status:string;frequency:string;start_date:string;end_date:string|null;visit_price:number;discount_percent:number;customer:{first_name:string;last_name:string|null}|null}
const freq:Record<string,string>={weekly:"Chaque semaine",biweekly:"Toutes les 2 semaines",monthly:"Chaque mois",custom:"Personnalisée"}
function ContractsPage(){const [rows,setRows]=useState<Contract[]>([]);useEffect(()=>{void load()},[]);async function load(){const {data}=await supabase.from("service_contracts").select("id,title,status,frequency,start_date,end_date,visit_price,discount_percent,customer:customers(first_name,last_name)").order("created_at",{ascending:false});setRows((data??[]) as unknown as Contract[])}return <div className="space-y-6"><header><p className="text-sm font-semibold text-emerald-700">CLIENTÈLE RÉCURRENTE</p><h1 className="mt-1 text-3xl font-bold">Contrats de service</h1><p className="mt-1 text-slate-600">Suivez les engagements récurrents, rabais et prochaines périodes de service.</p></header><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">Client</th><th className="px-4 py-3 text-left">Contrat</th><th className="px-4 py-3 text-left">Fréquence</th><th className="px-4 py-3 text-left">Période</th><th className="px-4 py-3 text-right">Prix/visite</th><th className="px-4 py-3 text-right">Rabais</th><th className="px-4 py-3">Statut</th></tr></thead><tbody className="divide-y">{rows.length===0?<tr><td colSpan={7} className="p-8 text-center text-slate-500">Aucun contrat récurrent pour le moment.</td></tr>:rows.map(c=><tr key={c.id}><td className="px-4 py-3 font-medium">{c.customer?`${c.customer.first_name} ${c.customer.last_name??""}`:"—"}</td><td className="px-4 py-3">{c.title}</td><td className="px-4 py-3">{freq[c.frequency]??c.frequency}</td><td className="px-4 py-3">{formatDate(c.start_date)}{c.end_date?` → ${formatDate(c.end_date)}`:""}</td><td className="px-4 py-3 text-right font-semibold">{formatCad(c.visit_price)}</td><td className="px-4 py-3 text-right">{c.discount_percent}%</td><td className="px-4 py-3 text-center"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{c.status}</span></td></tr>)}</tbody></table></div></div>}
