import { useEffect, useState } from "react"
import { createFileRoute, useNavigate } from "@tanstack/react-router"
import { z } from "zod"
import { requireActiveAdmin } from "@/features/admin/requireAdmin"
import { supabase } from "@/lib/supabase"
import { sendCrmEmail } from "@/lib/email-notifications"

const searchSchema=z.object({estimateId:z.string().optional()})
export const Route=createFileRoute("/admin/jobs/new")({validateSearch:searchSchema,component:NewJobPage})
type Customer={id:string;first_name:string;last_name:string|null;address_line:string|null;city:string|null;province:string|null;postal_code:string|null}
type Employee={id:string;first_name:string;last_name:string|null}
function localValue(date:Date){const d=new Date(date.getTime()-date.getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
function NewJobPage(){const navigate=useNavigate();const {estimateId}=Route.useSearch();const [customers,setCustomers]=useState<Customer[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [customerId,setCustomerId]=useState("");const [employeeId,setEmployeeId]=useState("");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [start,setStart]=useState("");const [end,setEnd]=useState("");const [address,setAddress]=useState("");const [city,setCity]=useState("");const [province,setProvince]=useState("ON");const [postal,setPostal]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false)
 useEffect(()=>{void load()},[estimateId])
 async function load(){try{if(!(await requireActiveAdmin())){await navigate({to:"/admin/login"});return}const [c,e]=await Promise.all([supabase.from("customers").select("id,first_name,last_name,address_line,city,province,postal_code").order("first_name"),supabase.from("employees").select("id,first_name,last_name").eq("status","active").order("first_name")]);if(c.error)throw c.error;if(e.error)throw e.error;setCustomers((c.data??[]) as Customer[]);setEmployees((e.data??[]) as Employee[]);if(estimateId){const {data,error}=await supabase.from("estimates").select("id,title,status,customer_id,estimated_duration_minutes,customer:customers(address_line,city,province,postal_code)").eq("id",estimateId).maybeSingle();if(error)throw error;if(data){setCustomerId(data.customer_id);setTitle(data.title||"Intervention issue du devis");const customer=(data as any).customer;setAddress(customer?.address_line||"");setCity(customer?.city||"");setProvince(customer?.province||"ON");setPostal(customer?.postal_code||"");const {data:booking}=await supabase.from("estimate_bookings").select("starts_at,ends_at,status").eq("estimate_id",estimateId).eq("status","reserved").maybeSingle();if(booking){setStart(localValue(new Date(booking.starts_at)));setEnd(localValue(new Date(booking.ends_at)))}else if(data.estimated_duration_minutes){const now=new Date();now.setMinutes(Math.ceil(now.getMinutes()/30)*30,0,0);setStart(localValue(now));setEnd(localValue(new Date(now.getTime()+Number(data.estimated_duration_minutes)*60000)))}}}}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.")}}
 function chooseCustomer(id:string){setCustomerId(id);const c=customers.find(x=>x.id===id);if(c){setAddress(c.address_line||"");setCity(c.city||"");setProvince(c.province||"ON");setPostal(c.postal_code||"")}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!customerId||!title.trim()){setError("Le client et le titre sont obligatoires.");return}setSaving(true);setError("");try{const user=await requireActiveAdmin();if(!user){await navigate({to:"/admin/login"});return}const payload={customer_id:customerId,estimate_id:estimateId||null,assigned_employee_id:employeeId||null,title:title.trim(),description:description||null,status:start?"scheduled":"unscheduled",scheduled_start:start?new Date(start).toISOString():null,scheduled_end:end?new Date(end).toISOString():null,address_line:address||null,city:city||null,province:province||null,postal_code:postal||null,created_by:user.id,updated_by:user.id};const {data,error}=await supabase.from("jobs").insert(payload).select("id").single();if(error)throw error;if(estimateId){await supabase.from("estimates").update({status:"converted_to_job",updated_by:user.id,updated_at:new Date().toISOString()}).eq("id",estimateId);await supabase.from("estimate_bookings").update({status:"converted",updated_at:new Date().toISOString()}).eq("estimate_id",estimateId).eq("status","reserved")}else if(start){const notification=await sendCrmEmail({type:"appointment_proposed",jobId:data.id});if(!notification.ok)console.warn("Job created, but appointment email was not sent.")}await navigate({to:"/admin/jobs/$jobId",params:{jobId:data.id}})}catch(e){setError(e instanceof Error?e.message:"Création impossible.")}finally{setSaving(false)}}
 return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="text-3xl font-bold">Nouvelle intervention</h1><p className="mt-1 text-slate-600">Créez le travail, affectez une personne et choisissez une date.</p></header>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}<form onSubmit={submit} className="space-y-6"><section className="grid gap-5 rounded-xl border bg-white p-6 shadow-sm sm:grid-cols-2"><Field label="Client *"><select value={customerId} onChange={e=>chooseCustomer(e.target.value)} className="w-full rounded-lg border px-3 py-2" required><option value="">Choisir un client</option>{customers.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name??""}</option>)}</select></Field><Field label="Employé affecté"><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="w-full rounded-lg border px-3 py-2"><option value="">Non affecté</option>{employees.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name??""}</option>)}</select></Field><Field label="Titre *" wide><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full rounded-lg border px-3 py-2" required/></Field><Field label="Description" wide><textarea value={description} onChange={e=>setDescription(e.target.value)} className="w-full rounded-lg border px-3 py-2 min-h-28"/></Field></section><section className="grid gap-5 rounded-xl border bg-white p-6 shadow-sm sm:grid-cols-2"><Field label="Début"><input type="datetime-local" value={start} onChange={e=>{setStart(e.target.value);if(e.target.value&&!end){const d=new Date(e.target.value);d.setHours(d.getHours()+2);setEnd(localValue(d))}}} className="w-full rounded-lg border px-3 py-2"/></Field><Field label="Fin"><input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></Field><Field label="Adresse"><input value={address} onChange={e=>setAddress(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></Field><Field label="Ville"><input value={city} onChange={e=>setCity(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></Field><Field label="Province"><input value={province} onChange={e=>setProvince(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></Field><Field label="Code postal"><input value={postal} onChange={e=>setPostal(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></Field></section><div className="flex justify-end"><button disabled={saving} className="rounded-lg bg-emerald-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?"Création…":"Créer l’intervention"}</button></div></form></div>}
function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`text-sm font-medium ${wide?"sm:col-span-2":""}`}>{label}<div className="mt-1">{children}</div></label>}
