import { createFileRoute, useNavigate } from "@tanstack/react-router"
import { useEffect, useMemo, useState } from "react"
import { BarChart3, Download, RefreshCw, TrendingUp } from "lucide-react"
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { PageHeader } from "@/components/admin/PageHeader"
import { requireActiveAdmin } from "@/features/admin/requireAdmin"
import { formatCad } from "@/features/admin/formatters"
import { supabase } from "@/lib/supabase"

export const Route = createFileRoute("/admin/reports")({ component: ReportsPage })

type RangeKey = "30d" | "90d" | "year" | "all"
type Payment = { amount:number; payment_date:string; invoice_id:string|null }
type Invoice = { id:string; total:number; amount_paid:number; balance_due:number; status:string; issue_date:string; created_at:string; customer_id:string; estimate_id:string|null }
type Estimate = { id:string; status:string; total:number; created_at:string; service_request_id:string|null }
type Request = { id:string; service_name:string|null; status:string; created_at:string }
type Job = { id:string; status:string; created_at:string; updated_at:string }
type Customer = { id:string; created_at:string }
type Partner = { id:string; status:string; created_at:string }
type PartnerApplication = { id:string; application_type:string|null; applicant_type:string|null; review_status:string|null; updated_at:string }
type InventoryItem = { id:string; name:string; category:string|null; quantity:number; unit_cost:number; reorder_level:number; status:string; updated_at:string }
type InventoryMovement = { id:string; movement_type:string; quantity_change:number; created_at:string }
type FinanceTx = { id:string; transaction_date:string; direction:string; classification:string; category:string; total:number; paid_by:string|null; partner_name:string|null; is_void:boolean; source_type:string|null }

function startFor(range: RangeKey) {
  const now = new Date()
  if (range === "all") return null
  if (range === "year") return new Date(now.getFullYear(), 0, 1)
  const days = range === "30d" ? 30 : 90
  return new Date(now.getTime() - days * 86400000)
}
function inRange(value:string|undefined|null, start:Date|null){ return !start || (!!value && new Date(value) >= start) }
function monthKey(value:string){ const d=new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}` }
function monthLabel(key:string){ const [y,m]=key.split("-"); return new Intl.DateTimeFormat("en-CA",{month:"short",year:"2-digit"}).format(new Date(Number(y),Number(m)-1,1)) }
function csvCell(value:unknown){ const s=String(value ?? ""); return `"${s.replaceAll('"','""')}"` }

function ReportsPage(){
  const nav=useNavigate(); const [range,setRange]=useState<RangeKey>("90d"); const [loading,setLoading]=useState(true); const [error,setError]=useState("")
  const [payments,setPayments]=useState<Payment[]>([]); const [invoices,setInvoices]=useState<Invoice[]>([]); const [estimates,setEstimates]=useState<Estimate[]>([]); const [requests,setRequests]=useState<Request[]>([]); const [jobs,setJobs]=useState<Job[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [partners,setPartners]=useState<Partner[]>([]); const [partnerApplications,setPartnerApplications]=useState<PartnerApplication[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]); const [movements,setMovements]=useState<InventoryMovement[]>([]); const [finance,setFinance]=useState<FinanceTx[]>([])
  useEffect(()=>{void load()},[])
  async function load(){ setLoading(true); setError(""); try{ if(!(await requireActiveAdmin())){await nav({to:"/admin/login"});return} const [p,i,e,r,j,c,pa,pap,inv,mv,ft]=await Promise.all([
    supabase.from("payments").select("amount,payment_date,invoice_id").order("payment_date"),
    supabase.from("invoices").select("id,total,amount_paid,balance_due,status,issue_date,created_at,customer_id,estimate_id").order("created_at"),
    supabase.from("estimates").select("id,status,total,created_at,service_request_id").order("created_at"),
    supabase.from("service_requests").select("id,service_name,status,created_at").order("created_at"),
    supabase.from("jobs").select("id,status,created_at,updated_at").order("created_at"),
    supabase.from("customers").select("id,created_at").order("created_at"),
    supabase.from("partners").select("id,status,created_at").order("created_at"),
    supabase.from("partner_applications").select("id,application_type,applicant_type,review_status,updated_at").order("updated_at"),
    supabase.from("inventory_items").select("id,name,category,quantity,unit_cost,reorder_level,status,updated_at").order("name"),
    supabase.from("inventory_movements").select("id,movement_type,quantity_change,created_at").order("created_at"),
    supabase.from("finance_transactions").select("id,transaction_date,direction,classification,category,total,paid_by,partner_name,is_void,source_type").eq("is_void",false).order("transaction_date")
  ]); const failed=[p,i,e,r,j,c,pa,pap,inv,mv,ft].find(x=>x.error); if(failed?.error) throw failed.error; setPayments((p.data??[]) as Payment[]);setInvoices((i.data??[]) as Invoice[]);setEstimates((e.data??[]) as Estimate[]);setRequests((r.data??[]) as Request[]);setJobs((j.data??[]) as Job[]);setCustomers((c.data??[]) as Customer[]);setPartners((pa.data??[]) as Partner[]);setPartnerApplications((pap.data??[]) as PartnerApplication[]);setInventory((inv.data??[]) as InventoryItem[]);setMovements((mv.data??[]) as InventoryMovement[]);setFinance((ft.data??[]) as FinanceTx[])
  }catch(e){setError(e instanceof Error?e.message:"Unable to load reports.")}finally{setLoading(false)} }
  const report=useMemo(()=>{ const start=startFor(range); const ps=payments.filter(x=>inRange(x.payment_date,start)); const ins=invoices.filter(x=>inRange(x.issue_date||x.created_at,start)); const es=estimates.filter(x=>inRange(x.created_at,start)); const rs=requests.filter(x=>inRange(x.created_at,start)); const js=jobs.filter(x=>inRange(x.created_at,start)); const cs=customers.filter(x=>inRange(x.created_at,start)); const pas=partnerApplications.filter(x=>inRange(x.updated_at,start)); const newPartners=partners.filter(x=>inRange(x.created_at,start)); const mvs=movements.filter(x=>inRange(x.created_at,start)); const fts=finance.filter(x=>inRange(x.transaction_date,start));
    const revenue=ps.reduce((s,x)=>s+Number(x.amount||0),0); const invoiced=ins.reduce((s,x)=>s+Number(x.total||0),0); const outstanding=ins.reduce((s,x)=>s+Number(x.balance_due||0),0); const accepted=es.filter(x=>["accepted","signed","approved"].includes(x.status)).length; const sent=es.filter(x=>x.status!=="draft").length; const conversion=sent?accepted/sent*100:0; const completed=js.filter(x=>x.status==="completed").length;
    const monthly=new Map<string,number>(); ps.forEach(x=>monthly.set(monthKey(x.payment_date),(monthly.get(monthKey(x.payment_date))??0)+Number(x.amount||0))); const monthlyRevenue=[...monthly.entries()].sort().map(([month,value])=>({month:monthLabel(month),value}));
    const serviceCounts=new Map<string,number>(); rs.forEach(x=>{const k=x.service_name||"Unspecified";serviceCounts.set(k,(serviceCounts.get(k)??0)+1)}); const services=[...serviceCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([service,count])=>({service,count}));
    const statusCounts=new Map<string,number>(); rs.forEach(x=>statusCounts.set(x.status,(statusCounts.get(x.status)??0)+1));
    const activePartners=partners.filter(x=>x.status==="active").length; const partnerApps=pas.filter(x=>x.application_type!=="subcontracting_client").length; const subcontracting=pas.filter(x=>x.application_type==="subcontracting_client").length; const openSubcontracting=partnerApplications.filter(x=>x.application_type==="subcontracting_client"&&x.review_status!=="rejected").length;
    const activeInventory=inventory.filter(x=>x.status==="active"); const inventoryValue=activeInventory.reduce((sum,x)=>sum+Number(x.quantity||0)*Number(x.unit_cost||0),0); const lowStock=activeInventory.filter(x=>Number(x.quantity)<=Number(x.reorder_level)).length; const stockOut=Math.abs(mvs.filter(x=>Number(x.quantity_change)<0).reduce((sum,x)=>sum+Number(x.quantity_change||0),0));
    const avgInvoice=ins.length?invoiced/ins.length:0; const operatingRevenue=fts.filter(x=>x.direction==="income").reduce((s,x)=>s+Number(x.total||0),0); const operatingExpenses=fts.filter(x=>x.direction==="expense"&&["operating_expense","employee_contractor"].includes(x.classification)).reduce((s,x)=>s+Number(x.total||0),0); const operatingResult=operatingRevenue-operatingExpenses; const capitalGross=fts.filter(x=>x.classification==="capital_asset").reduce((s,x)=>s+Number(x.total||0),0); const capitalRemoved=fts.filter(x=>x.classification==="capital_adjustment").reduce((s,x)=>s+Number(x.total||0),0); const capitalPurchases=Math.max(0,capitalGross-capitalRemoved); const partnerDue=fts.filter(x=>x.direction==="expense"&&["Partner 1","Partner 2"].includes(x.paid_by??"")).reduce((s,x)=>s+Number(x.total||0),0)+fts.filter(x=>x.direction==="funding"&&x.category==="Partner advance").reduce((s,x)=>s+Number(x.total||0),0)-fts.filter(x=>x.category==="Partner reimbursement").reduce((s,x)=>s+Number(x.total||0),0);
    return {revenue,invoiced,outstanding,requests:rs.length,customers:cs.length,invoices:ins.length,payments:ps.length,jobs:js.length,completed,conversion,monthlyRevenue,services,statuses:[...statusCounts.entries()].sort((a,b)=>b[1]-a[1]),activePartners,newPartners:newPartners.length,partnerApps,subcontracting,openSubcontracting,inventoryItems:activeInventory.length,inventoryValue,lowStock,stockMovements:mvs.length,stockOut,avgInvoice,operatingRevenue,operatingExpenses,operatingResult,capitalPurchases,partnerDue}
  },[range,payments,invoices,estimates,requests,jobs,customers,partners,partnerApplications,inventory,movements,finance])
  function exportCsv(){ const rows=[["Metric","Value"],["Revenue received",report.revenue],["Invoiced",report.invoiced],["Outstanding",report.outstanding],["Quote requests",report.requests],["New customers",report.customers],["Invoices",report.invoices],["Payments",report.payments],["Jobs",report.jobs],["Completed jobs",report.completed],["Quote conversion %",report.conversion.toFixed(1)],["Average invoice",report.avgInvoice],["Active partners",report.activePartners],["New partners",report.newPartners],["Partner applications",report.partnerApps],["Subcontracting opportunities",report.subcontracting],["Open subcontracting opportunities",report.openSubcontracting],["Inventory items",report.inventoryItems],["Inventory value",report.inventoryValue],["Low stock items",report.lowStock],["Stock movements",report.stockMovements],["Operating revenue (Finance)",report.operatingRevenue],["Operating expenses (Finance)",report.operatingExpenses],["Operating result (Finance)",report.operatingResult],["Equipment / capital purchases",report.capitalPurchases],["Estimated amount due to partners",report.partnerDue],[],["Month","Revenue"],...report.monthlyRevenue.map(x=>[x.month,x.value]),[],["Service","Quote requests"],...report.services.map(x=>[x.service,x.count])]; const csv=rows.map(r=>r.map(csvCell).join(",")).join("\r\n"); const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a");a.href=url;a.download=`omsg-report-${range}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url) }
  return <div className="space-y-6"><PageHeader title="Reports" description="Business performance, revenue, sales and operational activity." action={<div className="flex flex-wrap gap-2"><select value={range} onChange={e=>setRange(e.target.value as RangeKey)} className="rounded-lg border bg-white px-3 py-2 text-sm"><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="year">This year</option><option value="all">All time</option></select><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Refresh</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><Download className="h-4 w-4"/>Export CSV</button></div>}/>
    {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}{loading?<div className="rounded-xl border bg-white p-10 text-center text-slate-500">Loading reports…</div>:<>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Revenue received" value={formatCad(report.revenue)} note={`${report.payments} payment(s)`}/><Metric label="Invoiced" value={formatCad(report.invoiced)} note={`${report.invoices} invoice(s)`}/><Metric label="Outstanding" value={formatCad(report.outstanding)} note="Current balance due"/><Metric label="Quote conversion" value={`${report.conversion.toFixed(1)}%`} note="Accepted ÷ sent quotes"/></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Quote requests" value={String(report.requests)}/><Metric label="New customers" value={String(report.customers)}/><Metric label="Jobs" value={String(report.jobs)} note={`${report.completed} completed`}/><Metric label="Average payment" value={formatCad(report.payments?report.revenue/report.payments:0)}/></section>
    <section><h2 className="mb-3 text-lg font-bold">Finance</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Operating revenue" value={formatCad(report.operatingRevenue)} note="Includes automatic customer payments"/><Metric label="Operating expenses" value={formatCad(report.operatingExpenses)}/><Metric label="Operating result" value={formatCad(report.operatingResult)}/><Metric label="Equipment / capital" value={formatCad(report.capitalPurchases)}/><Metric label="Due to partners" value={formatCad(Math.max(0,report.partnerDue))} note="Advances + personally-paid expenses − reimbursements"/></div></section>
    <section><h2 className="mb-3 text-lg font-bold">Partners & subcontracting</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active partners" value={String(report.activePartners)} note={`${report.newPartners} added in period`}/><Metric label="Partner applications" value={String(report.partnerApps)}/><Metric label="Subcontracting opportunities" value={String(report.subcontracting)} note={`${report.openSubcontracting} currently open/contacted`}/><Metric label="Average invoice" value={formatCad(report.avgInvoice)}/></div></section>
    <section><h2 className="mb-3 text-lg font-bold">Inventory</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active inventory items" value={String(report.inventoryItems)}/><Metric label="Inventory value" value={formatCad(report.inventoryValue)} note="Quantity × unit cost"/><Metric label="Low stock alerts" value={String(report.lowStock)} note="At or below reorder level"/><Metric label="Stock movements" value={String(report.stockMovements)} note={`${report.stockOut.toFixed(1)} units issued in period`}/></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><ChartCard title="Revenue by month" icon={<TrendingUp className="h-5 w-5 text-emerald-600"/>}>{report.monthlyRevenue.length?<ResponsiveContainer width="100%" height={280}><BarChart data={report.monthlyRevenue}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`$${Math.round(Number(v))}`}/><Tooltip formatter={(v)=>formatCad(Number(v))}/><Bar dataKey="value" fill="currentColor" className="text-emerald-600" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<Empty/>}</ChartCard><ChartCard title="Quote requests by service" icon={<BarChart3 className="h-5 w-5 text-emerald-600"/>}>{report.services.length?<ResponsiveContainer width="100%" height={280}><BarChart data={report.services} layout="vertical" margin={{left:20}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="service" width={120} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" fill="currentColor" className="text-emerald-600" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer>:<Empty/>}</ChartCard></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Quote request status</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{report.statuses.length?report.statuses.map(([status,count])=><div key={status} className="rounded-lg bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{status.replaceAll("_"," ")}</p><p className="mt-1 text-2xl font-bold">{count}</p></div>):<p className="text-sm text-slate-500">No data for this period.</p>}</div></section></>}</div>
}
function Metric({label,value,note}:{label:string;value:string;note?:string}){return <article className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p>{note&&<p className="mt-1 text-xs text-slate-500">{note}</p>}</article>}
function ChartCard({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-2">{icon}<h2 className="font-bold">{title}</h2></div>{children}</section>}
function Empty(){return <div className="flex h-[280px] items-center justify-center text-sm text-slate-500">No data for this period.</div>}
