import { useEffect, useMemo, useState } from "react"
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router"
import { addMonths, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, startOfMonth, startOfWeek, subMonths } from "date-fns"
import { frCA } from "date-fns/locale"
import { ChevronLeft, ChevronRight } from "lucide-react"
import { requireActiveAdmin } from "@/features/admin/requireAdmin"
import { supabase } from "@/lib/supabase"

export const Route = createFileRoute("/admin/schedule")({ component: SchedulePage })

type Job = { id:string; job_number:string; title:string; status:string; scheduled_start:string; scheduled_end:string|null; customer:{first_name:string;last_name:string|null}|null }
type Booking = { id:string; estimate_id:string; starts_at:string; ends_at:string; status:string; estimate:{estimate_number:string;title:string|null}|null; customer:{first_name:string;last_name:string|null}|null }
type Block = { id:string; starts_at:string; ends_at:string; reason:string|null }

function localInputValue(date: Date) { const d = new Date(date.getTime() - date.getTimezoneOffset()*60000); return d.toISOString().slice(0,16) }

function SchedulePage(){
  const navigate=useNavigate(); const [month,setMonth]=useState(startOfMonth(new Date())); const [jobs,setJobs]=useState<Job[]>([]); const [bookings,setBookings]=useState<Booking[]>([]); const [blocks,setBlocks]=useState<Block[]>([]); const [error,setError]=useState(""); const [saving,setSaving]=useState(false)
  const [blockStart,setBlockStart]=useState(()=>localInputValue(new Date())); const [blockEnd,setBlockEnd]=useState(()=>localInputValue(new Date(Date.now()+60*60*1000))); const [reason,setReason]=useState("Indisponible")
  useEffect(()=>{void load()},[month])
  async function load(){try{if(!(await requireActiveAdmin())){await navigate({to:"/admin/login"});return}const from=startOfWeek(startOfMonth(month),{weekStartsOn:1}).toISOString();const to=endOfWeek(endOfMonth(month),{weekStartsOn:1}).toISOString();const [jobResult,bookingResult,blockResult]=await Promise.all([supabase.from("jobs").select("id,job_number,title,status,scheduled_start,scheduled_end,customer:customers(first_name,last_name)").gte("scheduled_start",from).lte("scheduled_start",to).neq("status","cancelled").order("scheduled_start"),supabase.from("estimate_bookings").select("id,estimate_id,starts_at,ends_at,status,estimate:estimates(estimate_number,title),customer:customers(first_name,last_name)").gte("starts_at",from).lte("starts_at",to).eq("status","reserved").order("starts_at"),supabase.from("schedule_blocks").select("id,starts_at,ends_at,reason").gte("starts_at",from).lte("starts_at",to).order("starts_at")]);if(jobResult.error)throw jobResult.error;if(bookingResult.error)throw bookingResult.error;if(blockResult.error)throw blockResult.error;setJobs((jobResult.data??[]) as unknown as Job[]);setBookings((bookingResult.data??[]) as unknown as Booking[]);setBlocks((blockResult.data??[]) as Block[])}catch(e){setError(e instanceof Error?e.message:"Calendrier impossible à charger.")}}
  async function addBlock(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const user=await requireActiveAdmin();if(!user)return;const {error:insertError}=await supabase.from("schedule_blocks").insert({starts_at:new Date(blockStart).toISOString(),ends_at:new Date(blockEnd).toISOString(),reason:reason.trim()||null,created_by:user.id});if(insertError)throw insertError;await load()}catch(e){setError(e instanceof Error?e.message:"Impossible de bloquer le créneau.")}finally{setSaving(false)}}
  async function removeBlock(id:string){const {error:deleteError}=await supabase.from("schedule_blocks").delete().eq("id",id);if(deleteError)setError(deleteError.message);else await load()}
  const days=useMemo(()=>{const first=startOfWeek(startOfMonth(month),{weekStartsOn:1});const last=endOfWeek(endOfMonth(month),{weekStartsOn:1});const result:Date[]=[];for(let d=first;d<=last;d=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1))result.push(d);return result},[month])
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Planification</p><h1 className="text-3xl font-bold">Calendrier</h1><p className="mt-1 text-slate-600">Interventions confirmées, réservations clients et périodes indisponibles.</p></div><div className="flex items-center gap-2"><button onClick={()=>setMonth(subMonths(month,1))} className="rounded-lg border bg-white p-2"><ChevronLeft/></button><button onClick={()=>setMonth(startOfMonth(new Date()))} className="rounded-lg border bg-white px-4 py-2 font-semibold">Aujourd’hui</button><button onClick={()=>setMonth(addMonths(month,1))} className="rounded-lg border bg-white p-2"><ChevronRight/></button></div></header>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>}
  <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Bloquer une période</h2><form onSubmit={addBlock} className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><input type="datetime-local" value={blockStart} onChange={e=>setBlockStart(e.target.value)} className="rounded-lg border px-3 py-2" required/><input type="datetime-local" value={blockEnd} onChange={e=>setBlockEnd(e.target.value)} className="rounded-lg border px-3 py-2" required/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison" className="rounded-lg border px-3 py-2"/><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-50">Bloquer</button></form></section>
  <h2 className="text-xl font-bold capitalize">{format(month,"MMMM yyyy",{locale:frCA})}</h2><div className="flex flex-wrap gap-3 text-xs"><span className="rounded-full bg-emerald-100 px-3 py-1 font-semibold text-emerald-800">Intervention</span><span className="rounded-full bg-blue-100 px-3 py-1 font-semibold text-blue-800">Réservation client</span><span className="rounded-full bg-slate-200 px-3 py-1 font-semibold text-slate-700">Indisponible</span></div>
  <section className="overflow-x-auto rounded-xl border bg-white shadow-sm"><div className="min-w-[980px]"><div className="grid grid-cols-7 border-b bg-slate-100 text-center text-sm font-semibold">{["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(x=><div key={x} className="p-3">{x}</div>)}</div><div className="grid grid-cols-7">{days.map(day=>{const dayJobs=jobs.filter(j=>isSameDay(new Date(j.scheduled_start),day));const dayBookings=bookings.filter(b=>isSameDay(new Date(b.starts_at),day));const dayBlocks=blocks.filter(b=>isSameDay(new Date(b.starts_at),day));return <div key={day.toISOString()} className={`min-h-40 border-b border-r p-2 ${isSameMonth(day,month)?"bg-white":"bg-slate-50 text-slate-400"}`}><div className={`mb-2 text-sm font-semibold ${isSameDay(day,new Date())?"inline-flex h-7 w-7 items-center justify-center rounded-full bg-emerald-600 text-white":""}`}>{format(day,"d")}</div><div className="space-y-1">{dayJobs.map(j=><Link key={j.id} to="/admin/jobs/$jobId" params={{jobId:j.id}} className="block rounded-md border-l-4 border-emerald-500 bg-emerald-50 p-2 text-xs text-slate-800 hover:bg-emerald-100"><p className="font-bold">{format(new Date(j.scheduled_start),"HH:mm")} · {j.title}</p><p className="truncate">{j.customer?`${j.customer.first_name} ${j.customer.last_name??""}`:j.job_number}</p></Link>)}{dayBookings.map(b=><Link key={b.id} to="/admin/estimates/$estimateId" params={{estimateId:b.estimate_id}} className="block rounded-md border-l-4 border-blue-500 bg-blue-50 p-2 text-xs text-slate-800 hover:bg-blue-100"><p className="font-bold">{format(new Date(b.starts_at),"HH:mm")} · Réservé</p><p className="truncate">{b.customer?`${b.customer.first_name} ${b.customer.last_name??""}`:b.estimate?.estimate_number}</p></Link>)}{dayBlocks.map(b=><button key={b.id} onClick={()=>void removeBlock(b.id)} title="Cliquer pour supprimer le blocage" className="block w-full rounded-md border-l-4 border-slate-500 bg-slate-100 p-2 text-left text-xs text-slate-700"><p className="font-bold">{format(new Date(b.starts_at),"HH:mm")}–{format(new Date(b.ends_at),"HH:mm")}</p><p className="truncate">{b.reason||"Indisponible"}</p></button>)}</div></div>})}</div></div></section></div>
}
