/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CommercialCleaningOttawaRouteImport } from './routes/commercial-cleaning-ottawa'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HandymanOttawaRouteImport } from './routes/handyman-ottawa'
import { Route as HouseCleaningOttawaRouteImport } from './routes/house-cleaning-ottawa'
import { Route as LandscapingOttawaRouteImport } from './routes/landscaping-ottawa'
import { Route as MobileCarDetailingOttawaRouteImport } from './routes/mobile-car-detailing-ottawa'
import { Route as MobileTireChangeOttawaRouteImport } from './routes/mobile-tire-change-ottawa'
import { Route as MovingServicesOttawaRouteImport } from './routes/moving-services-ottawa'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SnowRemovalOttawaRouteImport } from './routes/snow-removal-ottawa'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminContractsIndexRouteImport } from './routes/admin/contracts.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers.$customerId'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers.new'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees.index'
import { Route as AdminEstimatesIndexRouteImport } from './routes/admin/estimates.index'
import { Route as AdminEstimatesEstimateIdRouteImport } from './routes/admin/estimates.$estimateId'
import { Route as AdminEstimatesNewRouteImport } from './routes/admin/estimates.new'
import { Route as AdminInvoicesIndexRouteImport } from './routes/admin/invoices.index'
import { Route as AdminInvoicesInvoiceIdRouteImport } from './routes/admin/invoices.$invoiceId'
import { Route as AdminInvoicesNewRouteImport } from './routes/admin/invoices.new'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs.index'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin/jobs.$jobId'
import { Route as AdminJobsNewRouteImport } from './routes/admin/jobs.new'
import { Route as AdminPartnersIndexRouteImport } from './routes/admin/partners.index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments.index'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin/quotes.index'
import { Route as AdminQuotesRequestIdRouteImport } from './routes/admin/quotes.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialCleaningOttawaRoute =
  CommercialCleaningOttawaRouteImport.update({
    id: '/commercial-cleaning-ottawa',
    path: '/commercial-cleaning-ottawa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HandymanOttawaRoute = HandymanOttawaRouteImport.update({
  id: '/handyman-ottawa',
  path: '/handyman-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseCleaningOttawaRoute = HouseCleaningOttawaRouteImport.update({
  id: '/house-cleaning-ottawa',
  path: '/house-cleaning-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const LandscapingOttawaRoute = LandscapingOttawaRouteImport.update({
  id: '/landscaping-ottawa',
  path: '/landscaping-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileCarDetailingOttawaRoute =
  MobileCarDetailingOttawaRouteImport.update({
    id: '/mobile-car-detailing-ottawa',
    path: '/mobile-car-detailing-ottawa',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileTireChangeOttawaRoute = MobileTireChangeOttawaRouteImport.update({
  id: '/mobile-tire-change-ottawa',
  path: '/mobile-tire-change-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingServicesOttawaRoute = MovingServicesOttawaRouteImport.update({
  id: '/moving-services-ottawa',
  path: '/moving-services-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SnowRemovalOttawaRoute = SnowRemovalOttawaRouteImport.update({
  id: '/snow-removal-ottawa',
  path: '/snow-removal-ottawa',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsIndexRoute = AdminContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstimatesIndexRoute = AdminEstimatesIndexRouteImport.update({
  id: '/estimates/',
  path: '/estimates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstimatesEstimateIdRoute =
  AdminEstimatesEstimateIdRouteImport.update({
    id: '/estimates/$estimateId',
    path: '/estimates/$estimateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEstimatesNewRoute = AdminEstimatesNewRouteImport.update({
  id: '/estimates/new',
  path: '/estimates/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesIndexRoute = AdminInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesInvoiceIdRoute = AdminInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesNewRoute = AdminInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersIndexRoute = AdminPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRequestIdRoute = AdminQuotesRequestIdRouteImport.update({
  id: '/quotes/$requestId',
  path: '/quotes/$requestId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/commercial-cleaning-ottawa': typeof CommercialCleaningOttawaRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/handyman-ottawa': typeof HandymanOttawaRoute
  '/house-cleaning-ottawa': typeof HouseCleaningOttawaRoute
  '/landscaping-ottawa': typeof LandscapingOttawaRoute
  '/mobile-car-detailing-ottawa': typeof MobileCarDetailingOttawaRoute
  '/mobile-tire-change-ottawa': typeof MobileTireChangeOttawaRoute
  '/moving-services-ottawa': typeof MovingServicesOttawaRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snow-removal-ottawa': typeof SnowRemovalOttawaRoute
  '/terms': typeof TermsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/estimates/': typeof AdminEstimatesIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/commercial-cleaning-ottawa': typeof CommercialCleaningOttawaRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/handyman-ottawa': typeof HandymanOttawaRoute
  '/house-cleaning-ottawa': typeof HouseCleaningOttawaRoute
  '/landscaping-ottawa': typeof LandscapingOttawaRoute
  '/mobile-car-detailing-ottawa': typeof MobileCarDetailingOttawaRoute
  '/mobile-tire-change-ottawa': typeof MobileTireChangeOttawaRoute
  '/moving-services-ottawa': typeof MovingServicesOttawaRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snow-removal-ottawa': typeof SnowRemovalOttawaRoute
  '/terms': typeof TermsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/contracts': typeof AdminContractsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/estimates': typeof AdminEstimatesIndexRoute
  '/admin/invoices': typeof AdminInvoicesIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/partners': typeof AdminPartnersIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/commercial-cleaning-ottawa': typeof CommercialCleaningOttawaRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/handyman-ottawa': typeof HandymanOttawaRoute
  '/house-cleaning-ottawa': typeof HouseCleaningOttawaRoute
  '/landscaping-ottawa': typeof LandscapingOttawaRoute
  '/mobile-car-detailing-ottawa': typeof MobileCarDetailingOttawaRoute
  '/mobile-tire-change-ottawa': typeof MobileTireChangeOttawaRoute
  '/moving-services-ottawa': typeof MovingServicesOttawaRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/snow-removal-ottawa': typeof SnowRemovalOttawaRoute
  '/terms': typeof TermsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/invoices/new': typeof AdminInvoicesNewRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/contracts/': typeof AdminContractsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/estimates/': typeof AdminEstimatesIndexRoute
  '/admin/invoices/': typeof AdminInvoicesIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/commercial-cleaning-ottawa'
    | '/contact'
    | '/faq'
    | '/handyman-ottawa'
    | '/house-cleaning-ottawa'
    | '/landscaping-ottawa'
    | '/mobile-car-detailing-ottawa'
    | '/mobile-tire-change-ottawa'
    | '/moving-services-ottawa'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/snow-removal-ottawa'
    | '/terms'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/new'
    | '/admin/quotes/$requestId'
    | '/admin/contracts/'
    | '/admin/customers/'
    | '/admin/employees/'
    | '/admin/estimates/'
    | '/admin/invoices/'
    | '/admin/jobs/'
    | '/admin/partners/'
    | '/admin/payments/'
    | '/admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/commercial-cleaning-ottawa'
    | '/contact'
    | '/faq'
    | '/handyman-ottawa'
    | '/house-cleaning-ottawa'
    | '/landscaping-ottawa'
    | '/mobile-car-detailing-ottawa'
    | '/mobile-tire-change-ottawa'
    | '/moving-services-ottawa'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/snow-removal-ottawa'
    | '/terms'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/new'
    | '/admin/quotes/$requestId'
    | '/admin/contracts'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/estimates'
    | '/admin/invoices'
    | '/admin/jobs'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/commercial-cleaning-ottawa'
    | '/contact'
    | '/faq'
    | '/handyman-ottawa'
    | '/house-cleaning-ottawa'
    | '/landscaping-ottawa'
    | '/mobile-car-detailing-ottawa'
    | '/mobile-tire-change-ottawa'
    | '/moving-services-ottawa'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/snow-removal-ottawa'
    | '/terms'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/settings'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/new'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/new'
    | '/admin/quotes/$requestId'
    | '/admin/contracts/'
    | '/admin/customers/'
    | '/admin/employees/'
    | '/admin/estimates/'
    | '/admin/invoices/'
    | '/admin/jobs/'
    | '/admin/partners/'
    | '/admin/payments/'
    | '/admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  CommercialCleaningOttawaRoute: typeof CommercialCleaningOttawaRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HandymanOttawaRoute: typeof HandymanOttawaRoute
  HouseCleaningOttawaRoute: typeof HouseCleaningOttawaRoute
  LandscapingOttawaRoute: typeof LandscapingOttawaRoute
  MobileCarDetailingOttawaRoute: typeof MobileCarDetailingOttawaRoute
  MobileTireChangeOttawaRoute: typeof MobileTireChangeOttawaRoute
  MovingServicesOttawaRoute: typeof MovingServicesOttawaRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SnowRemovalOttawaRoute: typeof SnowRemovalOttawaRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-cleaning-ottawa': {
      id: '/commercial-cleaning-ottawa'
      path: '/commercial-cleaning-ottawa'
      fullPath: '/commercial-cleaning-ottawa'
      preLoaderRoute: typeof CommercialCleaningOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handyman-ottawa': {
      id: '/handyman-ottawa'
      path: '/handyman-ottawa'
      fullPath: '/handyman-ottawa'
      preLoaderRoute: typeof HandymanOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-cleaning-ottawa': {
      id: '/house-cleaning-ottawa'
      path: '/house-cleaning-ottawa'
      fullPath: '/house-cleaning-ottawa'
      preLoaderRoute: typeof HouseCleaningOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landscaping-ottawa': {
      id: '/landscaping-ottawa'
      path: '/landscaping-ottawa'
      fullPath: '/landscaping-ottawa'
      preLoaderRoute: typeof LandscapingOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-car-detailing-ottawa': {
      id: '/mobile-car-detailing-ottawa'
      path: '/mobile-car-detailing-ottawa'
      fullPath: '/mobile-car-detailing-ottawa'
      preLoaderRoute: typeof MobileCarDetailingOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-tire-change-ottawa': {
      id: '/mobile-tire-change-ottawa'
      path: '/mobile-tire-change-ottawa'
      fullPath: '/mobile-tire-change-ottawa'
      preLoaderRoute: typeof MobileTireChangeOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-services-ottawa': {
      id: '/moving-services-ottawa'
      path: '/moving-services-ottawa'
      fullPath: '/moving-services-ottawa'
      preLoaderRoute: typeof MovingServicesOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snow-removal-ottawa': {
      id: '/snow-removal-ottawa'
      path: '/snow-removal-ottawa'
      fullPath: '/snow-removal-ottawa'
      preLoaderRoute: typeof SnowRemovalOttawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts/': {
      id: '/admin/contracts/'
      path: '/contracts'
      fullPath: '/admin/contracts/'
      preLoaderRoute: typeof AdminContractsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/': {
      id: '/admin/estimates/'
      path: '/estimates'
      fullPath: '/admin/estimates/'
      preLoaderRoute: typeof AdminEstimatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/$estimateId': {
      id: '/admin/estimates/$estimateId'
      path: '/estimates/$estimateId'
      fullPath: '/admin/estimates/$estimateId'
      preLoaderRoute: typeof AdminEstimatesEstimateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/new': {
      id: '/admin/estimates/new'
      path: '/estimates/new'
      fullPath: '/admin/estimates/new'
      preLoaderRoute: typeof AdminEstimatesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/': {
      id: '/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AdminInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/$invoiceId': {
      id: '/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices/new': {
      id: '/admin/invoices/new'
      path: '/invoices/new'
      fullPath: '/admin/invoices/new'
      preLoaderRoute: typeof AdminInvoicesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners/': {
      id: '/admin/partners/'
      path: '/partners'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AdminPartnersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/$requestId': {
      id: '/admin/quotes/$requestId'
      path: '/quotes/$requestId'
      fullPath: '/admin/quotes/$requestId'
      preLoaderRoute: typeof AdminQuotesRequestIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminEstimatesEstimateIdRoute: typeof AdminEstimatesEstimateIdRoute
  AdminEstimatesNewRoute: typeof AdminEstimatesNewRoute
  AdminInvoicesInvoiceIdRoute: typeof AdminInvoicesInvoiceIdRoute
  AdminInvoicesNewRoute: typeof AdminInvoicesNewRoute
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  AdminQuotesRequestIdRoute: typeof AdminQuotesRequestIdRoute
  AdminContractsIndexRoute: typeof AdminContractsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminEstimatesIndexRoute: typeof AdminEstimatesIndexRoute
  AdminInvoicesIndexRoute: typeof AdminInvoicesIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminPartnersIndexRoute: typeof AdminPartnersIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminEstimatesEstimateIdRoute: AdminEstimatesEstimateIdRoute,
  AdminEstimatesNewRoute: AdminEstimatesNewRoute,
  AdminInvoicesInvoiceIdRoute: AdminInvoicesInvoiceIdRoute,
  AdminInvoicesNewRoute: AdminInvoicesNewRoute,
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  AdminQuotesRequestIdRoute: AdminQuotesRequestIdRoute,
  AdminContractsIndexRoute: AdminContractsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminEstimatesIndexRoute: AdminEstimatesIndexRoute,
  AdminInvoicesIndexRoute: AdminInvoicesIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminPartnersIndexRoute: AdminPartnersIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  CommercialCleaningOttawaRoute: CommercialCleaningOttawaRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HandymanOttawaRoute: HandymanOttawaRoute,
  HouseCleaningOttawaRoute: HouseCleaningOttawaRoute,
  LandscapingOttawaRoute: LandscapingOttawaRoute,
  MobileCarDetailingOttawaRoute: MobileCarDetailingOttawaRoute,
  MobileTireChangeOttawaRoute: MobileTireChangeOttawaRoute,
  MovingServicesOttawaRoute: MovingServicesOttawaRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SnowRemovalOttawaRoute: SnowRemovalOttawaRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
