/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers.$customerId'
import { Route as AdminCustomersNewRouteImport } from './routes/admin/customers.new'
import { Route as AdminEstimatesIndexRouteImport } from './routes/admin/estimates.index'
import { Route as AdminEstimatesEstimateIdRouteImport } from './routes/admin/estimates.$estimateId'
import { Route as AdminEstimatesNewRouteImport } from './routes/admin/estimates.new'
import { Route as AdminQuotesIndexRouteImport } from './routes/admin/quotes.index'
import { Route as AdminQuotesRequestIdRouteImport } from './routes/admin/quotes.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomersNewRoute = AdminCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstimatesIndexRoute = AdminEstimatesIndexRouteImport.update({
  id: '/estimates/',
  path: '/estimates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstimatesEstimateIdRoute =
  AdminEstimatesEstimateIdRouteImport.update({
    id: '/estimates/$estimateId',
    path: '/estimates/$estimateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEstimatesNewRoute = AdminEstimatesNewRouteImport.update({
  id: '/estimates/new',
  path: '/estimates/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesIndexRoute = AdminQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRequestIdRoute = AdminQuotesRequestIdRouteImport.update({
  id: '/quotes/$requestId',
  path: '/quotes/$requestId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/estimates/': typeof AdminEstimatesIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/estimates': typeof AdminEstimatesIndexRoute
  '/admin/quotes': typeof AdminQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/customers/new': typeof AdminCustomersNewRoute
  '/admin/estimates/$estimateId': typeof AdminEstimatesEstimateIdRoute
  '/admin/estimates/new': typeof AdminEstimatesNewRoute
  '/admin/quotes/$requestId': typeof AdminQuotesRequestIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/estimates/': typeof AdminEstimatesIndexRoute
  '/admin/quotes/': typeof AdminQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/quotes/$requestId'
    | '/admin/customers/'
    | '/admin/estimates/'
    | '/admin/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/admin'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/quotes/$requestId'
    | '/admin/customers'
    | '/admin/estimates'
    | '/admin/quotes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/partners'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/login'
    | '/admin/'
    | '/admin/customers/$customerId'
    | '/admin/customers/new'
    | '/admin/estimates/$estimateId'
    | '/admin/estimates/new'
    | '/admin/quotes/$requestId'
    | '/admin/customers/'
    | '/admin/estimates/'
    | '/admin/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/new': {
      id: '/admin/customers/new'
      path: '/customers/new'
      fullPath: '/admin/customers/new'
      preLoaderRoute: typeof AdminCustomersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/': {
      id: '/admin/estimates/'
      path: '/estimates'
      fullPath: '/admin/estimates/'
      preLoaderRoute: typeof AdminEstimatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/$estimateId': {
      id: '/admin/estimates/$estimateId'
      path: '/estimates/$estimateId'
      fullPath: '/admin/estimates/$estimateId'
      preLoaderRoute: typeof AdminEstimatesEstimateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estimates/new': {
      id: '/admin/estimates/new'
      path: '/estimates/new'
      fullPath: '/admin/estimates/new'
      preLoaderRoute: typeof AdminEstimatesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/': {
      id: '/admin/quotes/'
      path: '/quotes'
      fullPath: '/admin/quotes/'
      preLoaderRoute: typeof AdminQuotesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes/$requestId': {
      id: '/admin/quotes/$requestId'
      path: '/quotes/$requestId'
      fullPath: '/admin/quotes/$requestId'
      preLoaderRoute: typeof AdminQuotesRequestIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminCustomersNewRoute: typeof AdminCustomersNewRoute
  AdminEstimatesEstimateIdRoute: typeof AdminEstimatesEstimateIdRoute
  AdminEstimatesNewRoute: typeof AdminEstimatesNewRoute
  AdminQuotesRequestIdRoute: typeof AdminQuotesRequestIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminEstimatesIndexRoute: typeof AdminEstimatesIndexRoute
  AdminQuotesIndexRoute: typeof AdminQuotesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminCustomersNewRoute: AdminCustomersNewRoute,
  AdminEstimatesEstimateIdRoute: AdminEstimatesEstimateIdRoute,
  AdminEstimatesNewRoute: AdminEstimatesNewRoute,
  AdminQuotesRequestIdRoute: AdminQuotesRequestIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminEstimatesIndexRoute: AdminEstimatesIndexRoute,
  AdminQuotesIndexRoute: AdminQuotesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
