-- CRM v2.5: reusable marketing analytics for current and future campaigns.
create table if not exists public.marketing_campaigns(id uuid primary key default gen_random_uuid(),platform text not null default 'meta',external_campaign_id text,name text not null,service text,objective text,status text not null default 'draft',locations text[] not null default '{}',daily_budget numeric(12,2),planned_budget numeric(12,2),start_date date,end_date date,currency char(3) not null default 'CAD',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(platform,external_campaign_id));
create table if not exists public.marketing_campaign_daily_metrics(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references public.marketing_campaigns(id) on delete cascade,metric_date date not null,spend numeric(12,2) not null default 0,impressions bigint not null default 0,reach bigint not null default 0,clicks bigint not null default 0,conversations bigint not null default 0,leads bigint not null default 0,raw jsonb,synced_at timestamptz not null default now(),unique(campaign_id,metric_date));
create table if not exists public.marketing_breakdowns(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references public.marketing_campaigns(id) on delete cascade,metric_date date not null,dimension text not null,dimension_value text not null,spend numeric(12,2) not null default 0,impressions bigint not null default 0,reach bigint not null default 0,clicks bigint not null default 0,results bigint not null default 0,synced_at timestamptz not null default now(),unique(campaign_id,metric_date,dimension,dimension_value));
create table if not exists public.marketing_leads(id uuid primary key default gen_random_uuid(),campaign_id uuid references public.marketing_campaigns(id) on delete set null,service_request_id uuid references public.service_requests(id) on delete set null,customer_id uuid references public.customers(id) on delete set null,estimate_id uuid references public.estimates(id) on delete set null,source text not null default 'meta',external_lead_id text,contact_name text,contact_channel text,location text,age_range text,stage text not null default 'intake',quoted_value numeric(12,2) not null default 0,converted_revenue numeric(12,2) not null default 0,first_contact_at timestamptz not null default now(),converted_at timestamptz,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(source,external_lead_id));
create index if not exists marketing_metrics_campaign_date_idx on public.marketing_campaign_daily_metrics(campaign_id,metric_date desc);
create index if not exists marketing_leads_campaign_stage_idx on public.marketing_leads(campaign_id,stage);
alter table public.marketing_campaigns enable row level security; alter table public.marketing_campaign_daily_metrics enable row level security; alter table public.marketing_breakdowns enable row level security; alter table public.marketing_leads enable row level security;
do $$ declare t text; begin foreach t in array array['marketing_campaigns','marketing_campaign_daily_metrics','marketing_breakdowns','marketing_leads'] loop execute format('create policy "Admins manage %s" on public.%I for all to authenticated using (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true)) with check (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true))',t,t); end loop; exception when duplicate_object then null; end $$;
insert into public.marketing_campaigns(name,service,objective,status,locations,daily_budget,planned_budget,start_date,end_date) select 'Moving - Ottawa & Gatineau - Aug/Sep 2026','Moving','Messages','review',array['Ottawa, ON','Gatineau, QC'],10,70,'2026-08-31','2026-09-07' where not exists(select 1 from public.marketing_campaigns where name='Moving - Ottawa & Gatineau - Aug/Sep 2026');
