-- OMSG v2.6 - Quick expense entry foundation
-- Extends existing finance_transactions; preserves existing finance data.

alter table public.finance_transactions
  add column if not exists expense_scope text,
  add column if not exists service_category text,
  add column if not exists receipt_path text;

alter table public.finance_transactions drop constraint if exists finance_transactions_expense_scope_check;
alter table public.finance_transactions add constraint finance_transactions_expense_scope_check
check (expense_scope is null or expense_scope in ('general','service'));

create index if not exists finance_transactions_expense_scope_idx on public.finance_transactions(expense_scope);
create index if not exists finance_transactions_service_category_idx on public.finance_transactions(service_category);

create table if not exists public.finance_expense_categories (
  id bigint generated by default as identity primary key,
  category text not null unique,
  default_scope text not null default 'general' check (default_scope in ('general','service','either')),
  sort_order integer not null default 100,
  active boolean not null default true
);

insert into public.finance_expense_categories(category,default_scope,sort_order) values
('Advertising','either',10),('Website & Software','general',20),('Equipment','either',30),
('Moving Supplies','service',40),('Cleaning Supplies','service',50),('Vehicle / Fuel','either',60),
('Truck Rental','service',70),('Insurance','general',80),('Phone & Communications','general',90),
('Labour / Subcontractors','service',100),('Office & Administration','general',110),
('Training','either',120),('Professional Fees','general',130),('Other','either',999)
on conflict(category) do update set default_scope=excluded.default_scope,sort_order=excluded.sort_order,active=true;

alter table public.finance_expense_categories enable row level security;
drop policy if exists "Active admins manage finance expense categories" on public.finance_expense_categories;
create policy "Active admins manage finance expense categories" on public.finance_expense_categories
for all to authenticated
using (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true))
with check (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true));

create table if not exists public.finance_service_categories (
  id bigint generated by default as identity primary key,
  service_key text not null unique,
  service_name text not null,
  sort_order integer not null default 100,
  active boolean not null default true
);

insert into public.finance_service_categories(service_key,service_name,sort_order) values
('moving','Moving',10),('cleaning','Cleaning',20),('snow_removal','Snow Removal',30),
('landscaping','Landscaping / Property Maintenance',40),('handyman','Handyman / Small Renovations',50),
('mobile_tire_change','Mobile Tire Change',60),('car_detailing','Mobile Car Detailing',70)
on conflict(service_key) do update set service_name=excluded.service_name,sort_order=excluded.sort_order,active=true;

alter table public.finance_service_categories enable row level security;
drop policy if exists "Active admins manage finance service categories" on public.finance_service_categories;
create policy "Active admins manage finance service categories" on public.finance_service_categories
for all to authenticated
using (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true))
with check (exists(select 1 from public.admin_users au where au.id=auth.uid() and au.is_active=true));

create or replace view public.finance_today_expenses as
select transaction_date,count(*) as expense_count,coalesce(sum(total),0)::numeric(12,2) as total_spent
from public.finance_transactions
where direction='expense' and coalesce(is_void,false)=false and transaction_date=current_date
group by transaction_date;

grant select on public.finance_today_expenses to authenticated;
